
services:

  backend:
    build: ./Backend
    container_name: sportconnect_backend
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: app_sport_connect
      DB_USERNAME: sportconnect
      DB_PASSWORD: 123456
    volumes:
      - ./Backend:/var/www/html
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build: ./my-react-app
    container_name: sportconnect_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./my-react-app:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

  mysql:
    image: mysql:8.0
    container_name: sportconnect_mysql
    restart: always
    environment:
      MYSQL_DATABASE: app_sport_connect
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sportconnect
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

